server:
  port: 8080

camunda:
  bpm:
    client:
      base-url: http://localhost:8081/engine-rest

camunda-process:
  case-validation-key: "case-process-evaluation"

management:
  endpoints:
    web:
      exposure:
        include: "openapi, swagger-ui"
