server:
  port: 8080

camunda:
  bpm:
    client:
      base-url: http://localhost:8081/engine-rest

camunda-process:
  case-validation-key: "case-process-evaluation"
  calculate-risk-worker-topic: "calculate_risk_worker"

case-service:
  username: "user"
  password: "pass"

management:
  endpoints:
    web:
      exposure:
        include: "openapi, swagger-ui"
