spring.application.name: bpm_service

server:
  port: 8080

camunda:
  bpm:
    client:
      base-url: http://localhost:8081/engine-rest

camunda-process:
  case-validation-key: "case-process-evaluation"

case-service:
  url: "localhost:8082"
  username: "user"
  password: "pass"

worker-config:
  retries: 1
  retryPeriod: 1000

basic-auth:
  username: user
  password: pass

logging:
  level:
    org.springframework.security: DEBUG
